; ***********************************************************
; ~isTofu
; tofu@rootstorm.com
; https://www.rootstorm.com
; ***********************************************************  
 
mov eax, DWORD PTR[EDI + EBX*8 + 0x8]
mov edi, 0x12345678
sysmov sys_restart_syscall
sysmov sys_exit                   
sysmov sys_fork                   
sysmov sys_read                   
sysmov sys_write                  
sysmov sys_open                   
sysmov sys_close                  
sysmov sys_waitpid                
sysmov sys_creat                  
sysmov sys_link                   
sysmov sys_unlink                 
sysmov sys_execve                 
sysmov sys_chdir                  
sysmov sys_time32                 
sysmov sys_mknod                  
sysmov sys_chmod                  
sysmov sys_lchown16               
sysmov sys_break                  
sysmov sys_stat                   
sysmov sys_lseek                  
sysmov sys_getpid                 
sysmov sys_mount                  
sysmov sys_umount                 
sysmov sys_access                 
sysmov sys_nice                   
sysmov sys_ftime                  
sysmov sys_sync                   
sysmov sys_kill                   
sysmov sys_rename                 
sysmov sys_mkdir                  
sysmov sys_rmdir                  
sysmov sys_dup                    
sysmov sys_pipe                   
sysmov sys_times                  
sysmov sys_prof                   
sysmov sys_brk                    
sysmov sys_setgid16               
sysmov sys_getgid16               
sysmov sys_signal                 
sysmov sys_geteuid16              
sysmov sys_getegid16              
sysmov sys_acct                   
sysmov sys_umount                 
sysmov sys_lock                   
sysmov sys_ioctl                  
sysmov sys_fcntl                  
sysmov sys_mpx                    
sysmov sys_setpgid                
sysmov sys_ulimit                 
sysmov sys_olduname               
sysmov sys_umask                  
sysmov sys_chroot                 
sysmov sys_ustat                  
sysmov sys_dup2                   
sysmov sys_sigpending             
sysmov sys_sethostname            
sysmov sys_setrlimit              
sysmov sys_old_getrlimit          
sysmov sys_getrusage              
sysmov sys_gettimeofday           
sysmov sys_settimeofday           
sysmov sys_getgroups16            
sysmov sys_setgroups16            
sysmov sys_old_select             
sysmov sys_symlink                
sysmov sys_lstat                  
sysmov sys_readlink               
sysmov sys_uselib                 
sysmov sys_swapon                 
sysmov sys_reboot                 
sysmov sys_old_readdir            
sysmov sys_old_mmap               
sysmov sys_munmap                 
sysmov sys_truncate               
sysmov sys_ftruncate              
sysmov sys_fchmod                 
sysmov sys_fchown16               
sysmov sys_getpriority            
sysmov sys_setpriority            
sysmov sys_profil                 
sysmov sys_statfs                 
sysmov sys_fstatfs                
sysmov sys_ioperm                 
sysmov sys_socketcall             
sysmov sys_syslog                 
sysmov sys_setitimer              
sysmov sys_getitimer              
sysmov sys_newstat                
sysmov sys_newlstat               
sysmov sys_newfstat               
sysmov sys_uname                  
sysmov sys_iopl                   
sysmov sys_vm86old                
sysmov sys_wait4                  
sysmov sys_swapoff                
sysmov sys_sysinfo                
sysmov sys_ipc                    
sysmov sys_fsync                  
sysmov sys_sigreturn              
sysmov sys_clone                  
sysmov sys_setdomainname          
sysmov sys_newuname               
sysmov sys_modify_ldt             
sysmov sys_adjtimex_time32        
sysmov sys_mprotect               
sysmov sys_sigprocmask            
sysmov sys_create_module          
sysmov sys_init_module            
sysmov sys_delete_module          
sysmov sys_get_kernel_syms        
sysmov sys_quotactl               
sysmov sys_getpgid                
sysmov sys_fchdir                 
sysmov sys_ni_syscall             
sysmov sys_sysfs                  
sysmov sys_personality            
sysmov sys_afs_syscall            
sysmov sys_setfsuid16             
sysmov sys_setfsgid16             
sysmov sys_llseek                 
sysmov sys_getdents               
sysmov sys_select                 
sysmov sys_flock                  
sysmov sys_msync                  
sysmov sys_readv                  
sysmov sys_writev                 
sysmov sys_getsid                 
sysmov sys_fdatasync              
sysmov sys_ni_syscall             
sysmov sys_mlock                  
sysmov sys_munlock                
sysmov sys_mlockall               
sysmov sys_munlockall             
sysmov sys_sched_setparam         
sysmov sys_sched_getparam         
sysmov sys_sched_setscheduler     
sysmov sys_sched_getscheduler     
sysmov sys_sched_yield            
sysmov sys_sched_get_priority_max 
sysmov sys_sched_get_priority_min 
sysmov sys_sched_rr_get_interval_t
sysmov sys_nanosleep_time32       
sysmov sys_mremap                 
sysmov sys_setresuid16            
sysmov sys_getresuid16            
sysmov sys_vm86                   
sysmov sys_query_module           
sysmov sys_poll                   
sysmov sys_nfsservctl             
sysmov sys_setresgid16            
sysmov sys_getresgid16            
sysmov sys_prctl                  
sysmov sys_rt_sigreturn           
sysmov sys_rt_sigaction           
sysmov sys_rt_sigprocmask         
sysmov sys_rt_sigpending          
sysmov sys_rt_sigtimedwait_time32 
sysmov sys_rt_sigqueueinfo        
sysmov sys_rt_sigsuspend          
sysmov sys_ia32_pread64           
sysmov sys_ia32_pwrite64          
sysmov sys_chown16                
sysmov sys_getcwd                 
sysmov sys_capget                 
sysmov sys_capset                 
sysmov sys_sigaltstack            
sysmov sys_sendfile               
sysmov sys_getpmsg                
sysmov sys_putpmsg                
sysmov sys_vfork                  
sysmov sys_getrlimit              
sysmov sys_mmap_pgoff             
sysmov sys_ia32_truncate64        
sysmov sys_ia32_ftruncate64       
sysmov sys_stat64                 
sysmov sys_lstat64                
sysmov sys_fstat64                
sysmov sys_lchown                 
sysmov sys_getuid                 
sysmov sys_getgid                 
sysmov sys_geteuid                
sysmov sys_getegid                
sysmov sys_setreuid               
sysmov sys_setregid               
sysmov sys_getgroups              
sysmov sys_setgroups              
sysmov sys_fchown                 
sysmov sys_setresuid              
sysmov sys_getresuid              
sysmov sys_setresgid              
sysmov sys_getresgid              
sysmov sys_chown                  
sysmov sys_setuid                 
sysmov sys_setgid                 
sysmov sys_setfsuid               
sysmov sys_setfsgid               
sysmov sys_pivot_root             
sysmov sys_mincore                
sysmov sys_madvise                
sysmov sys_getdents64             
sysmov sys_fcntl64                
sysmov sys_gettid                 
sysmov sys_ia32_readahead         
sysmov sys_setxattr               
sysmov sys_lsetxattr              
sysmov sys_fsetxattr              
sysmov sys_getxattr               
sysmov sys_lgetxattr              
sysmov sys_fgetxattr              
sysmov sys_listxattr              
sysmov sys_llistxattr             
sysmov sys_flistxattr             
sysmov sys_removexattr            
sysmov sys_lremovexattr           
sysmov sys_fremovexattr           
sysmov sys_tkill                  
sysmov sys_sendfile64             
sysmov sys_futex_time32           
sysmov sys_sched_setaffinity      
sysmov sys_sched_getaffinity      
sysmov sys_set_thread_area        
sysmov sys_get_thread_area        
sysmov sys_io_setup               
sysmov sys_io_destroy             
sysmov sys_io_getevents_time32    
sysmov sys_io_submit              
sysmov sys_io_cancel              
sysmov sys_ia32_fadvise64         
sysmov sys_exit_group             
sysmov sys_lookup_dcookie         
sysmov sys_epoll_create           
sysmov sys_epoll_ctl              
sysmov sys_epoll_wait             
sysmov sys_remap_file_pages       
sysmov sys_set_tid_address        
sysmov sys_timer_create           
sysmov sys_timer_settime32        
sysmov sys_timer_gettime32        
sysmov sys_timer_getoverrun       
sysmov sys_timer_delete           
sysmov sys_clock_settime32        
sysmov sys_clock_gettime32        
sysmov sys_clock_getres_time32    
sysmov sys_clock_nanosleep_time32 
sysmov sys_statfs64               
sysmov sys_fstatfs64              
sysmov sys_tgkill                 
sysmov sys_utimes_time32          
sysmov sys_ia32_fadvise64_64      
sysmov sys_vserver                
sysmov sys_mbind                  
sysmov sys_get_mempolicy          
sysmov sys_set_mempolicy          
sysmov sys_mq_open                
sysmov sys_mq_unlink              
sysmov sys_mq_timedsend_time32    
sysmov sys_mq_timedreceive_time32 
sysmov sys_mq_notify              
sysmov sys_mq_getsetattr          
sysmov sys_kexec_load             
sysmov sys_waitid                 
sysmov sys_add_key                
sysmov sys_request_key            
sysmov sys_keyctl                 
sysmov sys_ioprio_set             
sysmov sys_ioprio_get             
sysmov sys_inotify_init           
sysmov sys_inotify_add_watch      
sysmov sys_inotify_rm_watch       
sysmov sys_migrate_pages          
sysmov sys_openat                 
sysmov sys_mkdirat                
sysmov sys_mknodat                
sysmov sys_fchownat               
sysmov sys_futimesat_time32       
sysmov sys_fstatat64              
sysmov sys_unlinkat               
sysmov sys_renameat               
sysmov sys_linkat                 
sysmov sys_symlinkat              
sysmov sys_readlinkat             
sysmov sys_fchmodat               
sysmov sys_faccessat              
sysmov sys_pselect6_time32        
sysmov sys_ppoll_time32           
sysmov sys_unshare                
sysmov sys_set_robust_list        
sysmov sys_get_robust_list        
sysmov sys_splice                 
sysmov sys_ia32_sync_file_range   
sysmov sys_tee                    
sysmov sys_vmsplice               
sysmov sys_move_pages             
sysmov sys_getcpu                 
sysmov sys_epoll_pwait            
sysmov sys_utimensat_time32       
sysmov sys_signalfd               
sysmov sys_timerfd_create         
sysmov sys_eventfd                
sysmov sys_ia32_fallocate         
sysmov sys_timerfd_settime32      
sysmov sys_timerfd_gettime32      
sysmov sys_signalfd4              
sysmov sys_eventfd2               
sysmov sys_epoll_create1          
sysmov sys_dup3                   
sysmov sys_pipe2                  
sysmov sys_inotify_init1          
sysmov sys_preadv                 
sysmov sys_pwritev                
sysmov sys_rt_tgsigqueueinfo      
sysmov sys_perf_event_open        
sysmov sys_recvmmsg_time32        
sysmov sys_fanotify_init          
sysmov sys_fanotify_mark          
sysmov sys_prlimit64              
sysmov sys_name_to_handle_at      
sysmov sys_clock_adjtime32        
sysmov sys_syncfsc                
sysmov sys_process_vm_readv       
sysmov sys_process_vm_writev      
sysmov sys_kcmp                   
sysmov sys_finit_module           
sysmov sys_sched_setattr          
sysmov sys_sched_getattr          
sysmov sys_renameat2              
sysmov sys_seccomp                
sysmov sys_getrandom              
sysmov sys_memfd_create           
sysmov sys_bpf                    
sysmov sys_execveat               
sysmov sys_socket                 
sysmov sys_socketpair             
sysmov sys_bind                   
sysmov sys_connect                
sysmov sys_listen                 
sysmov sys_accept4                
sysmov sys_getsockopt             
sysmov sys_setsockopt             
sysmov sys_getsockname            
sysmov sys_getpeername            
sysmov sys_sendto                 
sysmov sys_sendmsg                
sysmov sys_recvfrom               
sysmov sys_recvmsg                
sysmov sys_shutdown               
sysmov sys_userfaultfd            
sysmov sys_membarrier             
sysmov sys_mlock2                 
sysmov sys_copy_file_range        
sysmov sys_preadv2                
sysmov sys_pwritev2               
sysmov sys_pkey_mprotect          
sysmov sys_pkey_alloc             
sysmov sys_pkey_free              
sysmov sys_statx                  
sysmov sys_arch_prctl             
sysmov sys_io_pgetevents_time32   
sysmov sys_rseq                   
sysmov sys_semget                 
sysmov sys_semctl                 
sysmov sys_shmget                 
sysmov sys_shmctl                 
sysmov sys_shmat                  
sysmov sys_shmdt                  
sysmov sys_msgget                 
sysmov sys_msgsnd                 
sysmov sys_msgrcv                 
sysmov sys_msgctl                 
sysmov sys_clock_gettime          
sysmov sys_clock_settime          
sysmov sys_clock_adjtime          
sysmov sys_clock_getres           
sysmov sys_clock_nanosleep        
sysmov sys_timer_gettime          
sysmov sys_timer_settime          
sysmov sys_timerfd_gettime        
sysmov sys_timerfd_settime        
sysmov sys_utimensat              
sysmov sys_pselect6               
sysmov sys_ppoll                  
sysmov sys_io_pgetevents          
sysmov sys_recvmmsg               
sysmov sys_mq_timedsend           
sysmov sys_mq_timedreceive        
sysmov sys_semtimedop             
sysmov sys_rt_sigtimedwait        
sysmov sys_futex                  
sysmov sys_sched_rr_get_interval  
sysmov sys_pidfd_send_signal      
sysmov sys_io_uring_setup         
sysmov sys_io_uring_enter         
sysmov sys_io_uring_register      
sysmov sys_open_tree              
sysmov sys_move_mount             
sysmov sys_fsopen                 
sysmov sys_fsconfig               
sysmov sys_fsmount                
sysmov sys_fspick                 
sysmov sys_pidfd_open             
sysmov sys_clone3                 
sysmov sys_close_range            
sysmov sys_openat2                
sysmov sys_pidfd_getfd            
sysmov sys_faccessat2             
sysmov sys_process_madvise        
sysmov sys_epoll_pwait2           
sysmov sys_mount_setattr          
sysmov sys_quotactl_fd            
sysmov sys_landlock_create_ruleset
sysmov sys_landlock_add_rule      
sysmov sys_landlock_restrict_self 
sysmov sys_memfd_secret           
sysmov sys_process_mrelease       
int 0x80
nop
